### ISSUE TITLE
[Bug] Language problem

### ISSUE THREAD

**Issue by casinick** [ngocjohn/lunar-phase-card#12]
### Short summary 📝

The French language does not appear in the menu

### Detailed description 📋

I have just installed this magnificent card but the French language does not appear in the card configuration menu. If I manually change the language to "fr" it remains in English

### Version 📌

v1.2.0

### Environment 🌐

Core 2024.8.2 Supervisor 2024.08.0 Operating System 13.1 Interface utilisateur 20240809.0

### Logs and screenshots 📂

![Capture d'écran 2024-08-24 074336](https://github.com/user-attachments/assets/50643c6c-0a6c-4301-b0b8-c7ed51535b9e)

**Comment by ngocjohn** [comment]
Hi @casinick , FR will be in the next update.

**Comment by casinick** [comment]
Really sorry for my stupidity XD Thanks for your response and look forward to the next update :D

**Comment by carlone1** [comment]
Hi, in a future update you could add the Italian language. Thanks

**Comment by ngocjohn** [comment]
Hi @carlone1 , u can make a PR by this guide to add another translation 😃 https://github.com/ngocjohn/lunar-phase-card/blob/main/docs/CONTRIBUTING.md

**Comment by carlone1** [comment]
Hi, I tried to follow the guide you suggested but I was not able to do it. Thanks
