### ISSUE TITLE
[Feature] Detailed lunar information: make them dynamic?

### ISSUE THREAD

**Issue by Nickduino** [ngocjohn/lunar-phase-card#31]
### Short summary

Showing the direction, altitude, illumination and distance dynamically when the user hovers over the moon's trajectory would be interesting

### Detailed description

Currently, when you hover over the trajectory, it shows the elevation in an info box. Updating the detailed info too below would be fun

### Examples 🖼️

![image](https://github.com/user-attachments/assets/93165146-f51e-4914-b753-742b4a182f76)

**Comment by ngocjohn** [comment]
This is an interesting idea, I'll try to expand this information in the tooltip, instead of adding info for current time.

**Comment by Nickduino** [comment]
> I'll try to expand this information in the tooltip, instead of adding info for current time.

I thought you could **replace** the info for the current time with the info at the "hovered point". Then back to current when the cursor stops hovering over the trajectory.

But the tooltip works too...

**Comment by ngocjohn** [comment]
@Nickduino, I added a function to update the date simultaneously with hover over point. I will fix other bugs and release a new release 🎉 

![2024-11-02 21 33 09](https://github.com/user-attachments/assets/6c304c24-af46-459a-8e08-c4af8c574a67)

**Comment by Nickduino** [comment]
This is so cool! :heart:
