### ISSUE TITLE
[Bug] Detailed lunar information: the arrow is not pointing where it should

### ISSUE THREAD

**Issue by Nickduino** [ngocjohn/lunar-phase-card#34]
### Short summary 📝

The arrow should be pointing in the direction of the moon

### Detailed description 📋

It's pointing straight North when it should be south-west

![image](https://github.com/user-attachments/assets/7e09c551-4201-4e2e-afa7-42864f8ecff0)

### Version 📌

1.7

**Comment by ngocjohn** [comment]
@Nickduino Ah, I fix the unit and forgot about this. The new version has been added, it should show the correct direction. Please redownload

**Comment by Nickduino** [comment]
> The new version has been added, it should show the correct direction. Please redownload

I tried to redownload and clear the cash with [Ctrl] + [F5] but it's still not working
![image](https://github.com/user-attachments/assets/0d203a6f-14c6-4252-80a6-f4ec09abbfe4)
