### ISSUE TITLE
[Bug] Wrong German translations of the moon phases

### ISSUE THREAD

**Issue by NoRi2909** [ngocjohn/lunar-phase-card#42]
### Short summary 📝

The German translations of the moon phases are wrong

### Detailed description 📋

https://github.com/ngocjohn/lunar-phase-card/blob/61ae01852a747584b02ba481b1fb874628b9c3ab/src/languages/de.json#L5-L13

There is quite a lot wrong, here is a complete list of fixes:

```
 "phase": { 
     "firstQuarterMoon": "Zunehmender Halbmond", 
     "fullMoon": "Vollmond", 
     "thirdQuarterMoon": "Abnehmender Halbmond", 
     "newMoon": "Neumond", 
     "waxingCrescentMoon": "Zunehmender Sichelmond", 
     "waxingGibbousMoon": "Zunehm. Dreiviertelmond", 
     "waningCrescentMoon": "Abnehmender Sichelmond", 
     "waningGibbousMoon": "Abnehm. Dreiviertelmond" 

```

You can easily spot the main mistake as "Crescent" is "Sichelmond", and Gibbous is "Dreiviertelmond".
The current translation has this switched on the two "waning" lines.

On top of that it does not make sense to use the astronomer's terms "First Quarter" and "Third Quarter", that is no everyday language here. In German this is commonly referred to as "Halbmond" (half moon) because, well, it's one half of the moon at that time that is illuminated.

So to have a consistent terminology we use "Dreiviertel" (three-quarter) for the "Gibbous phases.

    Sichel   ->   Halb   ->    Dreiviertel    ->  Voll     and back

    Crescent ->   1/2    ->        3/4        ->  Full     and back

I edited the suggested change above to abbreviate "Zunehm." and "Abnehm." for "Dreiviertelmond" as this might not fit on mobile otherwise.

Edit: The German translation also adds "next" to these two strings which at first I found a good idea, but on mobile they don't fit anymore: 

https://github.com/ngocjohn/lunar-phase-card/blob/61ae01852a747584b02ba481b1fb874628b9c3ab/src/languages/de.json#L24-L25

So you might want to remove "Nächster " from both to align them with the English version.

Final note: "Altitude" is a very misleading term, that should be avoided by using "elevation" instead. As a result the German translation also uses "Höhe" (height or altitude) which is definitely incorrect for specifying an angle above or below the horizon. So at least fix that in German by using

      "altitude": "Elevation",

to avoid any misunderstanding and make it consistent with using "Azimut" (azimuth) for the horizontal angle.

### Version 📌

1.8.0

### Environment 🌐

Chrome OS 131

### Logs and screenshots 📂

This is what I got right after installing today:

![Screenshot 2024-11-18 19 16 42](https://github.com/user-attachments/assets/fcf33bc2-1258-4257-a529-eef7c594b8d8)

With almost 90% were still in a Gibbous phase and not at "Sichel" (crescent) as you see in the screenshot.
And the lunar phase integration right above has it correct (but there are also several errors in other phases in that one).

**Comment by Mikkooooo** [comment]
Hi ngocjohn ,
could you publish a new release with the corrected German translations for the lunar phase card  ?
It would be very helpful.
Thanks a lot

**Comment by NoRi2909** [comment]
@ngocjohn Thanks for the quick update. So much nicer to have the correct names now when scrolling through the view.

It looks like the two abbreviations I made along with the (current) "Dreiviertelmond" are not really necessary, they still seem to fit with the full "Abnehmender" and "Zunehmender" as you wrap to two lines for most longer texts anyhow.

I might update that in another PR. But to make it worth it you might want to add a few more strings from the UI to the files to translate.

One suggestion: Display the settings like "Southern Hemisphäre" or "Compact View", "Show background" etc. as toggles.
It's very easy to accidentally click one of those and not notice why something now looks wrong or different.

**Comment by ngocjohn** [comment]
@NoRi2909 Yes, I was also surprised that some languages have such long names for different phases... 😄  I'm thinking of improving the code to calculate the size of the text according to the scale of the card, I have a few more ideas I want to add to a future release. I will definitely add new strings for translation, for missing titles in the editor. I look forward to your PR for improving the card.. 👍  But there's not much time and a lot of work, creating custom cards is just my little hobby and I'm learning a lot about how everything works..

I also have a new project where I want a chart to track the sun and moon... What do you think? 😃 
 
![2024-11-20 16 43 20](https://github.com/user-attachments/assets/20e0c2c3-a420-4a30-a765-ab606856efa3)

**Comment by NoRi2909** [comment]
@ngocjohn Cool concept with the sun and moon card. Probably a bit too detailed for the home automation crowd where you are more interested in a nice big graphic overview like the lunar card.

But HA is developing in so many directions today. Your project is a cool idea to replace separate mobile apps by integrating this into the single HA app or website, something that is getting more and more interesting.

Speaking of the  home automation use: One problem I see with the current implementation is that the different views resize the card. This makes it very difficult to place it on a wall-mounted dashboard. So for that audience you should focus on making all views keep the same basic card size.

If you make them all the same size the user could even swipe from one view to the other which removes the need for the buttons in the upper right.

Alternative: Make the buttons optional so there is just a single view chosen in Edit mode for a fixed layout.

**Comment by ngocjohn** [comment]
@NoRi2909 Well, the original idea of the whole card was just basic moon phase information, then I gradually added a calendar, and then a chart. 🤣  The option for fixed default display in the configuration is also there. You can choose to have base, calendar, or chart as the initial view when you open the dashboard. I wanted to allow as much user customization as possible, according to your needs.. 😉

**Comment by NoRi2909** [comment]
@ngocjohn Yeah, those babies grow, bigger and bigger. 😄 

Regarding the default view: Yes, I can set that but the buttons remain active so the user can still change to a different view.
So for wall-mounted displays where the cards should not resize or move having an option block that is still needed.

Additional correction to my previous comment:
> One suggestion: Display the settings like "Southern Hemisphäre" or "Compact View", "Show background" etc. as toggles.
> It's very easy to accidentally click one of those and not notice why something now looks wrong or different.

There was some cache issue (I assume) that made the checkboxes on those disappear. That's why I made that comment.
So that has fixed itself …

**Comment by NoRi2909** [comment]
@ngocjohn One thing I just noticed while diving a bit deeper into the many cool details of your lunar-card:

On the calendar view page you have a "Close" button:

![image](https://github.com/user-attachments/assets/894211a6-11e1-4977-9779-e9c6f114c6ac)

Note that with text labels this becomes "Schließen" in German, so that might need more space than you'd expect.
So perhaps using a large [x] button might be a good solution here to remain safe. When hovering over the button it can still show the localized text using the tooltip.

Regardless, "Close", "Previous month" and "Next month" should be at the top of your list for adding to the strings file because they show up in the end-user UI, not just the settings.
