### ISSUE TITLE
[Bug] Make the use of "Azimuth" and "Elevation" consistent

### ISSUE THREAD

**Issue by NoRi2909** [ngocjohn/lunar-phase-card#47]
### Short summary 📝

Fix the inconsistent labels for both angles on Main and Graph pages

### Detailed description 📋

Currently the labels for "Elevation" ("Altitude") and "Azimuth" ("Direction") are used inconsistently in the UI:

On the main view it's
- Azimuth
- Altitude

and on the Graph view it's
- Direction
- Altitude

Both should be using
- Azimuth
- Elevation

instead which are the correct astronomical terms.

It's in the 1.9.0b3 - can't select that from the popup below.

### Version 📦

v1.8.1

### Logs and screenshots 📂

![image](https://github.com/user-attachments/assets/d8e2f20c-a9e9-42c4-8f2f-c24a2fce5371)

![image](https://github.com/user-attachments/assets/2765b082-ff61-48f2-b629-f05bdf4cc3be)

**Comment by ngocjohn** [comment]
Hi @NoRi2909, According to the available information I found this... 

# Astronomical Terms for Moon Position: Azimuth and Altitude

In astronomy, the correct terms to describe the Moon's position in the sky are **azimuth** and **altitude**. These terms are part of the **horizontal coordinate system**, which provides the Moon's location relative to an observer's horizon.

## Definitions

### **Azimuth**
- **Definition**: The angular measurement of the Moon's position along the horizon.
- **Measurement**: 
  - Measured in degrees from **north (0°)** clockwise:
    - **90°** = East
    - **180°** = South
    - **270°** = West

### **Altitude**
- **Definition**: The angular height of the Moon above the horizon.
- **Measurement**:
  - Measured in degrees:
    - **0°** = On the horizon
    - **90°** = Directly overhead (zenith)
    - Negative values indicate the Moon is **below the horizon**.

## Why **Altitude** and Not **Elevation**?
- **Altitude** is the standard term in **astronomy** for the vertical angle above the horizon.
- **Elevation** is often used in other contexts (e.g., geography or surveying) to describe height relative to sea level, but it is not typically used in astronomical settings.

## Astronomical Context
When describing the Moon's position in the celestial sphere, **azimuth** and **altitude** are used together to give its location in the **horizontal coordinate system**.

---

## Summary
The correct terms are **azimuth** and **altitude** when referring to the Moon's position in astronomy.

I think I'll just change the name for direction to azimuth. 
What bug exactly are you referring to in the beta version? In Beta version there is a new added graph type and in this one there is no added info, just a plain chart 😄

**Comment by NoRi2909** [comment]
Well, that's what AI summarizes because that is copied from source to source …

The Sun integration in Home Assistant uses Azimuth and Elevation, so for consistency within HA that could be the better choice.

Here is another app reference:

https://www.photopills.com/articles/understanding-azimuth-and-elevation

In German we definitely use Elevation, only.

So it's up to you to decide what you pick in English.
The main issue here is changing "Direction" to "Azimuth" so the app is consistent.

**Comment by ngocjohn** [comment]
@NoRi2909 Yes, I will change the German according to your suggestion, we will use Azimut & Elevation 👍
