### ISSUE TITLE
[Bug] Selecting "Horizon" as the default card does not work

### ISSUE THREAD

**Issue by NoRi2909** [ngocjohn/lunar-phase-card#49]
### Short summary 📝

"Horizon" seems to be some legacy view that is broken now

### Detailed description 📋

When you select "Horizon" from the 'Select default card' menu in settings the display is smaller and incomplete:

![image](https://github.com/user-attachments/assets/19f8119b-f97f-436e-a3a7-bd052447e069)

I assume this should be "Graph" instead, showing that view by default.

Besides that the "Dynamic" graph type is quite superior and keeps the default card size - a big plus.
Make that the only option, less is more!

1.9.0b4

### Version 📦

v1.8.1

**Comment by ngocjohn** [comment]
Fix will be added in the official release, the problem was the card size in sections mode. 👍
