### ISSUE TITLE
lunar-phase-card doesnt work in Fully Kiosk Browser

### ISSUE THREAD

**Issue by Schwippser** [ngocjohn/lunar-phase-card#58]
### Short summary 📝

lunar-phase-card doesnt work in Fully Kiosk Browser

### Detailed description 📋

I have a Galaxy Tab A7 and a Galaxy Tab A9+. Both devices are running Homeassistant with lunar-phase-card. The lunar-phase-card is displayed in Homeassistant companion app on both devices. I also use Fully Kiosk Browser on both devices. The lunar-phase-card is not displayed in Fully Kiosk Browser. 
Error-Message: Custom element doenst' exist: lunar-phase-card 

### Version 📦

v1.9.0

**Comment by ngocjohn** [comment]
Hi @Schwippser, just clear browser cache in fully kiosk

**Comment by Schwippser** [comment]
> Hi @Schwippser, just clear browser cache in fully kiosk

OK ... thanks ... it works
